from pathlib import Path

# Project directories
PROJECT_ROOT = Path(__file__).parent.parent
DB_ROOT = PROJECT_ROOT / 'db'
PDF_ROOT = PROJECT_ROOT / 'pdf_downloads'

# Ensure directories exist
DB_ROOT.mkdir(parents=True, exist_ok=True)
PDF_ROOT.mkdir(parents=True, exist_ok=True)

# Central configuration for Indonesian regulations (peraturan.go.id)
# Key: The identifier used for filenames and URL slugs (where applicable)
# Value: The relative path for the rekapitulasi page
PERATURAN_CONFIG = {
    "uu": "uu/rekapitulasi",
    "perppu": "perppu/rekapitulasi",
    "pp": "pp/rekapitulasi",
    "perpres": "perpres/rekapitulasi",
    "penpres": "penpres/rekapitulasi",
    "keppres": "keppres/rekapitulasi",
    "inpres": "inpres/rekapitulasi",
    "permenkominfo": "permen/permenkominfo",
    "permenkomdigi": "permen/permenkomdigi",
    "permenag": "permen/permenag",
    "permendagri": "permen/permendagri",
    "permen-esdm": "permen/permen-esdm",
    "permenkumham": "permen/permenkumham",
    "permenhut": "permen/permenhut",
    "permenkkp": "permen/permenkkp",
    "permenkes": "permen/permenkes",
    "permenkeu": "permen/permenkeu",
    "permenlu": "permen/permenlu",
    "permenkop-kukm": "permen/permenkop-kukm",
    "permenlh": "permen/permenlh",
    "permen-pppa": "permen/permen-pppa",
    "permenpanrb": "permen/permenpanrb",
    "permen-ppn-bappenas": "permen/permen-ppn-bappenas",
    "permenpera": "permen/permenpera",
    "permenristek": "permen/permenristek",
    "permenparekraf": "permen/permenparekraf",
    "permenpu": "permen/permenpu",
    "permendikbud": "permen/permendikbud",
    "permendag": "permen/permendag",
    "permenperin": "permen/permenperin",
    "permenhan": "permen/permenhan",
    "permentan": "permen/permentan",
    "permenakertrans": "permen/permenakertrans",
    "permen-bumn": "permen/permen-bumn",
    "permenbudpar": "permen/permenbudpar",
    "permenko-kesra": "permen/permenko-kesra",
    "permen-pdt": "permen/permen-pdt",
    "permendiknas": "permen/permendiknas",
    "permenhub": "permen/permenhub",
    "permensetneg": "permen/permensetneg",
    "permensetneg": "permen/permensetneg",
    "permen-atrbpn": "permen/permen-atrbpn",
    "permenaker": "permen/permenaker",
    "permen-pupr": "permen/permen-pupr",
    "permenko-perekonomian": "permen/permenko-perekonomian",
    "permenko-polhukam": "permen/permenko-polhukam",
    "permen-lhk": "permen/permen-lhk",
    "permenpar": "permen/permenpar",
    "permenristekdikti": "permen/permenristekdikti",
    "permenpora": "permen/permenpora",
    "permendesa": "permen/permendesa",
    "permenko-pmk": "permen/permenko-pmk",
    "permenko-maritim": "permen/permenko-maritim",
    "permenko-marves": "permen/permenko-marves",
    "permendikbudristek": "permen/permendikbudristek",
    "permenkum": "permen/permenkum",
    "permenham": "permen/permenham",
    "permenko+pangan": "permen/permenko+pangan",
    "permenimipas": "permen/permenimipas",
    "permenkoimipas": "permen/permenkoimipas",
    "permendespdt": "permen/permendespdt",
    "permentrans": "permen/permentrans",
    "permenkopemas": "permen/permenkopemas",
    "permen-lh": "permen/permen-lh",
    "permenkopermas": "permen/permenkopermas",
    "permenekraf": "permen/permenekraf",
    "permen-p2mi": "permen/permen-p2mi",
    "permenklhbph": "permen/permenklhbph",
    "permenkop": "permen/permenkop",
    "perukm": "permen/perukm",
    "permenpkp": "permen/permenpkp",
    "permenkopolkam": "permen/permenkopolkam",
    "permendikdasmen": "permen/permendikdasmen",
    "permendiktisaintek": "permen/permendiktisaintek",
    "permenkebud": "permen/permenkebud",
    "permenpkp2": "permen/permenpkp2",
    "permenkoinfra": "permen/permenkoinfra",
    "permen-haji-umrah": "permen/permen-haji-umrah",
    "perbagi": "perban/perbagi",
    "peraturan-kpk": "perban/peraturan-kpk",
    "peraturan-bkn": "perban/peraturan-bkn",
    "peraturan-bkpm": "perban/peraturan-bkpm",
    "peraturan-bmkg": "perban/peraturan-bmkg",
    "peraturan-bnn": "perban/peraturan-bnn",
    "peraturan-bnpb": "perban/peraturan-bnpb",
    "peraturan-bnpt": "perban/peraturan-bnpt",
    "peraturan-bnpp": "perban/peraturan-bnpp",
    "peraturan-bphmigas": "perban/peraturan-bphmigas",
    "peraturan-bpom": "perban/peraturan-bpom",
    "peraturan-bawaslu": "perban/peraturan-bawaslu",
    "peraturan-bapeten": "perban/peraturan-bapeten",
    "peraturan-bpkp": "perban/peraturan-bpkp",
    "peraturan-bpjs": "perban/peraturan-bpjs-kesehatan",
    "peraturan-bpn": "perban/peraturan-bpn",
    "peraturan-bps": "perban/peraturan-bps",
    "peraturan-basarnas": "perban/peraturan-basarnas",
    "peraturan-bsn": "perban/peraturan-bsn",
    "peraturan-batan": "perban/peraturan-batan",
    "peraturan-bwi": "perban/peraturan-bwi",
    "peraturan-dkpp": "perban/peraturan-dkpp",
    "peraturan-dpr": "perban/peraturan-dpr",
    "peraturan-kejakgung": "perban/peraturan-kejakgung",
    "peraturan-anri": "perban/peraturan-anri",
    "peraturan-komnasham": "perban/peraturan-komnasham",
    "peraturan-kpu": "perban/peraturan-kpu",
    "peraturan-ky": "perban/peraturan-ky",
    "peraturan-kki": "perban/peraturan-kki",
    "peraturan-lan": "perban/peraturan-lan",
    "peraturan-lipi": "perban/peraturan-lipi",
    "peraturan-lps": "perban/peraturan-lps",
    "peraturan-lpsk": "perban/peraturan-lpsk",
    "peraturan-lsn": "perban/peraturan-lsn",
    "peraturan-ma": "perban/peraturan-ma",
    "peraturan-ori": "perban/peraturan-ori",
    "peraturan-ppatk": "perban/peraturan-ppatk",
    "peraturan-polri": "perban/peraturan-polri",
    "peraturan-dpd": "perban/peraturan-dpd",
    "peraturan-bapedal": "perban/peraturan-bapedal",
    "peraturan-kpi": "perban/peraturan-kpi",
    "peraturan-lapan": "perban/peraturan-lapan",
    "peraturan-bpk": "perban/peraturan-bpk",
    "peraturan-ojk": "perban/peraturan-ojk",
    "peraturan-bi": "perban/peraturan-bi",
    "peraturan-mk": "perban/peraturan-mk",
    "peraturan-djsn": "perban/peraturan-djsn",
    "perpusnas": "perban/perpusnas",
    "peraturan-bnp2tki": "perban/peraturan-bnp2tki",
    "peraturan-lkpp": "perban/peraturan-lkpp",
    "peraturan-big": "perban/peraturan-big",
    "peraturan-kip": "perban/peraturan-kip",
    "peraturan-lpei": "perban/peraturan-lpei",
    "peraturan-kasn": "perban/peraturan-kasn",
    "peraturan-bpjs": "perban/peraturan-bpjs-ketenagakerjaan",
    "peraturan-bppt": "perban/peraturan-bppt",
    "peraturan-bakamla": "perban/peraturan-bakamla",
    "peraturan-bpip": "perban/peraturan-bpip",
    "peraturan-bppbk": "perban/peraturan-bppbk",
    "peraturan-bssn": "perban/peraturan-bssn",
    "peraturan-barekraf": "perban/peraturan-barekraf",
    "peraturan-baznas": "perban/peraturan-baznas",
    "peraturan-bnp2": "perban/peraturan-bnp2",
    "peraturan-bppkh": "perban/peraturan-bppkh",
    "peraturan-bkkbn": "perban/peraturan-bkkbn",
    "peraturan-bin": "perban/peraturan-bin",
    "peraturan-kppu": "perban/peraturan-kppu",
    "peraturan-dkpbpbb": "perban/peraturan-dkpbpbb",
    "peraturan-bppmi": "perban/peraturan-bppmi",
    "peraturan-bnsp": "perban/peraturan-bnsp",
    "peraturan-btpr": "perban/peraturan-btpr",
    "peraturan-denaskek": "perban/peraturan-denaskek",
    "peraturan-brin": "perban/peraturan-brin",
    "peraturan-bapanas": "perban/peraturan-bapanas",
    "peraturan-koin": "perban/peraturan-koin",
    "peraturan-bpjph": "perban/peraturan-bpjph",
    "perden": "perban/perden",
    "perbph": "perban/perbph",
    "perbanp2kin": "perban/perbanp2kin"
}

def get_rekapitulasi_filename(name):
    """Returns the filename for a rekapitulasi JSON file."""
    return str(DB_ROOT / f"peraturan_go_id_rekapitulasi_{name}.json")

def get_all_extracted_filename(name):
    """Returns the filename for an extracted 'all' JSON file."""
    return str(DB_ROOT / f"peraturan_go_id_all_{name}.json")

def get_metadata_filename(name):
    """Returns the filename for a metadata JSON file."""
    return str(DB_ROOT / f"peraturan_go_id_metadata_{name}.json")
